version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: weather-db
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: weather-api
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres

  serverless:
    build:
      context: .
      dockerfile: serverless/Dockerfile
    container_name: weather-serverless
    ports:
      - '3001:3001'
    environment:
      SERVERLESS_ACCESS_KEY: ${SERVERLESS_ACCESS_KEY}
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  pgdata:
