service: weather-file-processor

org: ${env:SERVERLESS_ORG_NAME}
app: weather-app

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  memorySize: 2048
  licenseKey: ${env:SERVERLESS_ACCESS_KEY}
  

  vpc:
    subnetIds:
      - ${env:SUBNET_1}
      - ${env:SUBNET_2}
      - ${env:SUBNET_3}
    securityGroupIds:
      - ${env:SG_ID}

  environment:
    BUCKET_NAME: ${env:BUCKET_NAME}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASS: ${env:DB_PASS}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetObject
        - s3:DeleteObject
        - s3:PutObject
        - s3:CopyObject
      Resource: arn:aws:s3:::${env:BUCKET_NAME}/*
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource: arn:aws:s3:::${env:BUCKET_NAME}

functions:
  processUpload:
    handler: src/file-processor.handler
    timeout: 60
    events:
      - s3:
          bucket: ${env:BUCKET_NAME}
          event: s3:ObjectCreated:*
          existing: true

package:
  individually: true

custom:
  esbuild:
    external:
      - '@project/shared'
    sourcemap: false
    minify: false
    target: node20
    platform: node
